### ISSUE TITLE
Dataset problem

### ISSUE THREAD

**Issue by zhangbaijin** [mevah/ExPGAN#8]
Hi,mevah,Thanks for your work,and what is frankfurt? How should i get it ?

**Comment by zhangbaijin** [comment]
There is no  frankfurt floder in gtFine

**Comment by aycatakmaz** [comment]
The `frankfurt` folder is not directly under the `gtFine` directory, but it is rather under the `gtFine/val` subdirectory. So the folder you need to move is `gtFine/val/frankfurt`.

**Comment by zhangbaijin** [comment]
O，thanks，but there is no&nbsp;frankfurt folder in gtFine/val,
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ayca Takmaz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 下午2:13
收件人:&nbsp;"mevah/ExPGAN"<ExPGAN@noreply.github.com&gt;;
抄送:&nbsp;"张晓峰南京邮电大学"<512631874@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mevah/ExPGAN] Dataset problem (#8)





 
The frankfurt folder is not directly under the gtFine directory, but it is rather under the gtFine/val subdirectory.

**Comment by aycatakmaz** [comment]
I downloaded and checked the current version of the dataset on the Cityscapes website, and it includes the `frankfurt` folder as well.

I recommend downloading the `gtFine_trainvaltest.zip` file again from the following link:
https://www.cityscapes-dataset.com/file-handling/?packageID=1

But in any case, we did not use that folder for training, and it was used only for the evaluation and comparison of the performances across different models. Since the image sequences in the original `test` directory did not have ground truth pixel-level segmentation information, we selected one of the `val` folders (`frankfurt`) to be the final test set. So you don't have to worry about that folder.

**Comment by zhangbaijin** [comment]
OK，thanks a lot！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ayca Takmaz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 下午2:30
收件人:&nbsp;"mevah/ExPGAN"<ExPGAN@noreply.github.com&gt;;
抄送:&nbsp;"张晓峰南京邮电大学"<512631874@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mevah/ExPGAN] Dataset problem (#8)





 
I downloaded checked the current version of the dataset on the Cityscapes website, and it includes the frankfurt folder as well.
 
I recommend downloading the gtFine_trainvaltest.zip file again from the following link:
 https://www.cityscapes-dataset.com/file-handling/?packageID=1
 
But in any case, we did not use that folder for training, and it was used only for the evaluation and comparison of the performances across different models. Since the image sequences in the original test directory did not have ground truth pixel-level segmentation information, we selected one of the val folders (frankfurt) to be the final test set. So you don't have to worry about that folder.
